name: build
on:
  push:
    branches:
      - test
jobs:
  build:
    name: Publish latest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and publish images
        run: ./scripts/build . test ${{ matrix.platform }}
