name: build
on:
  push:
    branches:
      - test
jobs:
  build:
    name: Publish latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build and publish images
        run: |
          ./scripts/build .
